language: rust
env:
  global:
    - secure: SuReUCElAROSnrioUxuJdE2kK5fMwmC+GeT0Ifi88VdG2VxbrVSOQOqTnSSW6xS2FrzXRGDlDeoIyk2i1hNERS0yc/ATe1hGF6TzMUq7zocA+VMcB4CaH79eNZy0NvHObqoySH08duVNikpQnriED9pFoJEZxj2UevQepj411Pw=
script:
  - cargo test -v
  - cargo doc -v
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
notifications:
  email: false